name: Prubea

on:
  push:
jobs:
  Prueba:
    name: Build & Test con JUnit 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Compilar
        run: mvn compile
      - name: Test
        run: mvn test
